---
- name: creating vpc
  hosts: localhost
  become: yes
  tasks: 
  - name: create vpc
    ec2_vpc_net:
      state: present
      name: myvpc10
      cidr_block: 192.168.0.0/16
      resource_tags: { "Env":"Dev" }
      region: us-east-2
      aws_access_key:
      aws_secret_key: 
