---
- name: Install and configure tomcat
  hosts: 52.87.182.37
  gather_facts: true
  become: yes
  tasks:
    - name: update repos
      apt:
        name: "*"
        state: latest
    - name: Installing OpenJDK
      apt:
        name: openjdk-9-jdk
    - name: Download tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.72/bin/apache-tomcat-9.0.72.tar.gz"
        dest: /usr/local/
    - name: Extracting tomcat
      unarchive:
        src: "/usr/local/apache-tomcat-9.0.72.tar.gz"
        dest: /usr/local
        remote_src: yes
    - name: renaming tomcat home
      command: mv /usr/local/apache-tomcat-9.0.72.tar.gz /usr/local/tomcat
      
       
  
